### ISSUE TITLE
Hemp plants overwhelming the landscape

### ISSUE THREAD

**Issue by MentalMouse** [EPIICTHUNDERCAT/HempFarmer#1]
The defaults for hemp spawning are 5000, leaving the entire world covered in hemp.  This is the version (numbered 0.0.1?) you left when you went on vacation.

**Comment by Roukurai** [comment]
Have you been able to stop this from happening? I lowered all the settings to 1 for all types, and still overpopulation. I am trying with generation set to false and spawn, but failed to get it done.

I will relaunch my client to see if it requires that for settings to kick in

**Comment by MentalMouse** [comment]
I wound up setting it all three to 1, and that did cut it down to where there's usually only a few in sight from any given spot on the landscape.  ;-)  Still fairly common, I'd like to be able to have them be a rare find.  I haven't checked if the value can be fractional, I hope so.

That said, "rare find" might not work so well just now, because they also seem to drop very few seeds, and often nothing at all.  I'm suspecting that at least some worldgen plants are created immature, but even some farmed plants that I would have sworn were mature, dropped nothing on harvest.  (I've tried shears too, doesn't seem to make a difference).

**Comment by EPIICTHUNDERCAT** [comment]
Hmm I’ll have to investigate

**Comment by EPIICTHUNDERCAT** [comment]
I havent been on my computer for a bit, my new job had me a little busy so i cant be on too much , however here soon ill be a little more active

**Comment by V10lator** [comment]
Fixed here: https://github.com/V10lator/HempFarmer/commit/17ea7d19ff3b732a271a0eb9588e913b04922704

Download (only available via IPv6) : https://nl01-v6.v10lator.de/hempfarmer-0.0.1.jar

Make sure to remove the config file before updating and be warned that this version has more changes (see https://github.com/V10lator/HempFarmer/commits/master )

//EDIT: @EPIICTHUNDERCAT Feel free to cherry-pick every change you like from my repo. :)

**Comment by EPIICTHUNDERCAT** [comment]
@V10lator i have my desktop now in my new location, ill take a look at ur fork, and merge if everything is fine, then ill push to Curse, thanks for keeping it going tho! i appreciate that, moved about 4 times in the last year so no chance i could work on it.

**Comment by EPIICTHUNDERCAT** [comment]
fixing
