### ISSUE TITLE
When Drying Hemp, I'm Given a Bucket

### ISSUE THREAD

**Issue by spruill7716** [EPIICTHUNDERCAT/HempFarmer#2]
This bug only occurs when using the regular hemp, straight from the crop. I place the hemp in a furnace to create dried hemp, however I'm given a bucket. I'm using coal as the fuel.

https://i.imgur.com/wXHKcde.png
https://i.imgur.com/6y2mktV.png

**Comment by EPIICTHUNDERCAT** [comment]
LOL!  How did I manage that! I’ll fix it when I get on a computer again. Soon!

**Comment by spruill7716** [comment]
Sounds good!

**Comment by V10lator** [comment]
Fixed here: https://github.com/V10lator/HempFarmer/commit/e5bb3bc957b2abc513b5050f89df0c98029108f3

Download (only available via IPv6) : https://nl01-v6.v10lator.de/hempfarmer-0.0.1.jar

Be warned that this version has more changes (see https://github.com/V10lator/HempFarmer/commits/master )

@EPIICTHUNDERCAT Feel free to cherry-pick every change you like from my repo. :)

**Comment by EPIICTHUNDERCAT** [comment]
@V10lator Pushing an update today, i know late, but itll make it easier, thanks for fixing those things!

Ill put u in the description, planning on updating this to the next versions too
